#!/usr/bin/env python3
"""Auto-generated by curl-to-skill (v1). POST https://api.resend.com/emails"""
import argparse
import json
import os
import sys
import urllib.error
import urllib.request

API_KEY_ENV = "RESEND_API_KEY"
URL = "https://api.resend.com/emails"
METHOD = "POST"
FIELDS = ['from', 'to', 'subject']


def main():
    parser = argparse.ArgumentParser(description="Call resend: POST https://api.resend.com/emails")
    for f in FIELDS:
        parser.add_argument(f"--{f}", required=True, help=f"value for '{f}'")
    parser.add_argument("--api-key", default=os.environ.get(API_KEY_ENV), help=f"API key (default: from {API_KEY_ENV} env var)")
    args = parser.parse_args()

    api_key = args.api_key
    if not api_key:
        print(f"Error: provide --api-key or set the {API_KEY_ENV} environment variable first.", file=sys.stderr)
        sys.exit(1)

    body = {f: getattr(args, f) for f in FIELDS}
    data = json.dumps(body).encode() if FIELDS else None

    req = urllib.request.Request(URL, data=data, method=METHOD)
    req.add_header("Authorization", f"Bearer {api_key}")
    if data is not None:
        req.add_header("Content-Type", "application/json")

    try:
        with urllib.request.urlopen(req) as resp:
            print(resp.read().decode())
    except urllib.error.HTTPError as e:
        print(f"HTTP {e.code}: {e.read().decode()}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
